workflows:
  ios-workflow:
    name: JABR iOS Build
    max_build_duration: 60
    environment:
      node: 20
      xcode: latest
      ios_signing:
        distribution_type: development
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npx vite build
      - name: Sync iOS
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/Build/Products/**/*.ipa
