workflows:
  ios-workflow:
    name: JABR iOS Build
    max_build_duration: 60
    environment:
      node: 20
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npx vite build
      - name: Sync iOS
        script: |
          npx cap sync ios
      - name: Archive build files
        script: |
          zip -r jabr-app.zip ios/App/
    artifacts:
      - jabr-app.zip
