workflows:
  ios-workflow:
    name: JABR iOS Build
    max_build_duration: 60
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Create simple build
        script: |
          mkdir -p dist/public
          cp -r client/* dist/public/
          cd dist/public && npm install
      - name: Setup Capacitor
        script: |
          npx cap add ios
      - name: Sync iOS
        script: |
          npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
